# Generated by Django 3.1.1 on 2020-09-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foxymaps', '0002_auto_20200908_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='grid_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='open_to_public',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_times',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
